name: Build and Deploy React Game

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          # Update package.json React version
          npm pkg set dependencies.react="^18.2.0" dependencies.react-dom="^18.2.0"
          # Install dependencies with legacy peer deps
          npm install --legacy-peer-deps
          npm install --save-dev @shadcn/ui --legacy-peer-deps
          # Initialize shadcn-ui with custom config to avoid prompt
          echo '{
            "style": "default",
            "rsc": false,
            "tailwind": {
              "config": "tailwind.config.js",
              "css": "src/index.css",
              "baseColor": "slate",
              "cssVariables": true
            },
            "aliases": {
              "components": "@/components",
              "utils": "@/lib/utils"
            }
          }' > components.json
          npx @shadcn/ui@latest init
          npx @shadcn/ui@latest add button card

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # or 'dist' if using Vite
          branch: gh-pages